version: "2"
services: 
    app:
        container_name: reviews_cnn_model
        build:
            context: ./
            dockerfile: Dockerfile
        ports: 
            - "5000:5000"
#https://towardsdatascience.com/how-to-deploy-ml-models-using-flask-gunicorn-nginx-docker-9b32055b3d0